name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - charts/**
      - modules/**
      - .github/workflows/release.yml
      - release-please-config.json
      - .release-please-manifest.json

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: charts/empty
            release-type: helm
          - path: modules/empty
            release-type: terraform-module
    steps:
      - uses: actions/checkout@main
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          path: ${{ matrix.path }}
          release-type: ${{ matrix.release-type }}
          include-component-in-tag: true
