name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - charts/**
      - modules/**
      - .github/workflows/release.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ github.token }}
          include-component-in-tag: true
          release-type: helm
          path: charts/empty
