name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - charts/**
      - modules/**
      - .github/workflows/release.yml
      - release-please-config.json
      - .release-please-manifest.json

permissions:
  contents: write
  pull-requests: write

jobs:
  identify:
    runs-on: ubuntu-latest
    outputs:
      packages: "${{ steps.changed.outputs.packages }}"
    steps:
      - uses: actions/checkout@main
      - id: changed
        shell: bash
        run: |
          DATA="[]"
          for x in $(find charts/ modules/ -mindepth 1 -maxdepth 1 -type d); do
            case ${x} in
              charts**)
                DATA=$(echo "${DATA}" | jq -c --raw-output --arg path "${x}" --arg type "helm" '.+= [{"path":$path,"release-type":$type}]')
                ;;
              modules**)
                DATA=$(echo "${DATA}" | jq -c --raw-output --arg path "${x}" --arg type "terraform-module" '.+= [{"path":$path,"release-type":$type}]')
                ;;
            esac
          done
          echo "packages=${DATA}" | tee -a ${GITHUB_OUTPUT}

  release:
    runs-on: ubuntu-latest
    needs: [identify]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.identify.outputs.packages) }}
          #- path: charts/empty
          #  release-type: helm
          #- path: modules/empty
          #  release-type: terraform-module
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          path: ${{ matrix.path }}
          release-type: ${{ matrix.release-type }}
          include-component-in-tag: true
